import { Link } from 'react-router-dom';
import { indicatorGroups, observationPrinciple, observationScale } from '../data/observationIndicators';
import type { TeacherObservationData } from '../types';
export function IndicatorAnalysis({ learnerId, observation }: { learnerId: string; observation?: TeacherObservationData }) {
  if (!observation) return <section className="card"><h2>No saved observation yet</h2><p>Complete and save a Teacher Observation for this learner to review the collected ratings.</p><Link className="button" to={`/learners/${learnerId}/observation`}>Go to Teacher Observation</Link></section>;
  return <div className="profile-form"><section className="card"><span className="pill subtle">Collected ratings · Analysis placeholder</span><h2>Teacher-provided observation summary</h2><p>No interpretation, scoring, rules, or recommendations have been applied. The values below are exactly the teacher’s saved observations.</p><dl className="observation-context"><div><dt>Learner</dt><dd>{observation.context.name} · {observation.context.learnerCode}</dd></div><div><dt>Class/grade · Subject</dt><dd>{observation.context.grade} · {observation.context.subject}</dd></div><div><dt>Date · Teacher</dt><dd>{observation.date} · {observation.teacher}</dd></div><div><dt>Activity/task</dt><dd>{observation.activity}</dd></div></dl></section>
    {indicatorGroups.map(group => <section className="card analysis-group" key={group.title}><h2>{group.title}</h2><div className="ratings-table-wrapper"><table className="ratings-table"><caption>{group.title} — saved 0–3 ratings and optional notes</caption><thead><tr><th scope="col">Indicator</th><th scope="col">Teacher rating</th><th scope="col">Teacher note</th></tr></thead><tbody>{group.indicators.map(indicator => { const value = observation.ratings[indicator.id]; return <tr key={indicator.id}><th scope="row">{indicator.label}</th><td><strong>{value.rating}</strong> · {observationScale[value.rating].label}</td><td>{value.note || 'No note recorded'}</td></tr>; })}</tbody></table></div></section>)}
    <section className="card"><h2>Additional teacher observation</h2><p className="preserve-text">{observation.additionalObservation || 'No additional observation recorded.'}</p><h3>Observed strengths during this activity</h3>{observation.observedStrengths.length ? <ul>{observation.observedStrengths.map(value => <li key={value}>{value}</li>)}</ul> : <p>None recorded.</p>}<h3>Observed barriers/difficulties</h3>{observation.observedBarriers.length ? <ul>{observation.observedBarriers.map(value => <li key={value}>{value}</li>)}</ul> : <p>None recorded.</p>}</section>
    <div className="note">{observationPrinciple}</div><Link className="button secondary" to={`/learners/${learnerId}/observation`}>← Review Teacher Observation</Link>
  </div>;
}
