import { useEffect, useState } from 'react';
import type { FormEvent } from 'react';
import { Link, useParams } from 'react-router-dom';
import { learners } from '../data/learners';
import type { Decision, LearnerWork } from '../types';
import { steps } from '../components/Layout';
import { PageHeading } from '../components/PageHeading';
export function LearnerWorkflow({ work, update }: { work: Record<string, LearnerWork>; update: (id: string, patch: Partial<LearnerWork>) => void }) {
  const { learnerId, stage } = useParams();
  const learner = learners.find(item => item.id === learnerId);
  const [saved, setSaved] = useState(false);
  useEffect(() => setSaved(false), [learnerId, stage]);
  if (!learner || !steps.some(([path]) => path === stage)) return <div className="card"><h1>Page not found</h1><Link to="/">Return to dashboard</Link></div>;
  const current = work[learner.id] ?? { observation: '', modification: '' };
  const index = steps.findIndex(([path]) => path === stage);
  const saveObservation = (event: FormEvent) => { event.preventDefault(); setSaved(true); };
  const choose = (decision: Decision) => update(learner.id, { decision });
  return <><Link className="back-link" to="/">← All learners</Link><PageHeading eyebrow={`${learner.name.toUpperCase()} · ${learner.grade.toUpperCase()}`} title={steps[index][1]} description={`Step ${index + 1} of 6 · A teacher-led path from observation to activity planning.`} /><div className="workflow-progress" aria-label="Workflow progress">{steps.map(([path, label], i) => <Link key={path} className={path === stage ? 'current' : ''} aria-current={path === stage ? 'step' : undefined} to={`/learners/${learner.id}/${path}`}><span>{i + 1}</span><small>{label}</small></Link>)}</div>
  {stage === 'profile' && <div className="two-columns"><section className="card"><span className="avatar large">{learner.initials}</span><h2>{learner.name}</h2><p>{learner.grade} · Fictional learner</p><h3>Strengths to build on</h3><ul>{learner.strengths.map(s => <li key={s}>{s}</li>)}</ul></section><section className="card"><p className="eyebrow">SUPPORT CONTEXT</p><h2>{learner.focus}</h2><p>This is a sample focus for exploring the workflow. Add a classroom observation to provide context for your reflection.</p><div className="note">Describe observable learning experiences, without diagnostic labels.</div></section></div>}
  {stage === 'observation' && <form className="card" onSubmit={saveObservation}><h2>What did you notice?</h2><p>Record the task, setting, learner response, and any support that helped.</p><label htmlFor="observation">Classroom observation</label><textarea id="observation" rows={6} placeholder="For example: During independent writing, the learner started after seeing a worked example…" value={current.observation} onChange={e => { update(learner.id, { observation: e.target.value }); setSaved(false); }} /><div className="form-actions"><button className="button" type="submit" disabled={!current.observation.trim()}>Save observation</button><span role="status">{saved ? 'Saved for this session.' : 'Stored in memory for this session only.'}</span></div></form>}
  {stage === 'analysis' && <section className="card"><span className="pill subtle">Illustrative placeholder</span><h2>Reflect on learning indicators</h2><p>No analysis has been performed. These are example areas a future transparent rule-based system could help organize.</p><div className="indicator-grid">{['Task initiation', 'Participation', 'Response to scaffolding'].map(s => <div className="indicator" key={s}><h3>{s}</h3><span>Awaiting teacher review</span></div>)}</div><h3>Your observation</h3><blockquote>{current.observation || 'No observation entered yet.'}</blockquote><div className="note">Indicators describe classroom experiences. They do not establish a diagnosis or learner category.</div></section>}
  {stage === 'recommendation' && <section className="card"><span className="pill subtle">Explainable recommendation · Sample</span><h2>Try a short, scaffolded activity</h2><p>Offer a worked example, a manageable first step, and a brief check-in.</p><h3>Why this example?</h3><p>A worked example can clarify expectations, and a short first step gives the teacher an opportunity to observe how the learner responds.</p><h3>Evidence and limitations</h3><p>This is a fixed demonstration recommendation. It is not generated from the learner’s observation. No rules or ML model currently run.</p><div className="note">Review suitability against your own observations, learner preferences, and classroom context before choosing an activity.</div></section>}
  {stage === 'decision' && <section className="card"><h2>You decide what happens next</h2><p>Review the sample activity and choose the support that fits your learner.</p><div className="decision-options">{(['accept', 'modify', 'reject'] as const).map(d => <button key={d} className={`decision-button ${current.decision === d ? 'selected' : ''}`} aria-pressed={current.decision === d} onClick={() => choose(d)}><strong>{d[0].toUpperCase() + d.slice(1)}</strong><span>{d === 'accept' ? 'Use the sample activity' : d === 'modify' ? 'Adapt it to your context' : 'Do not use this activity'}</span></button>)}</div>{current.decision === 'modify' && <><label htmlFor="modification">Your adapted activity</label><textarea id="modification" rows={4} value={current.modification} onChange={e => update(learner.id, { modification: e.target.value })} placeholder="Describe your changes to the activity…" /></>}<p role="status">{current.decision ? `Decision: ${current.decision}. Saved for this session.` : 'No decision selected yet.'}</p></section>}
  {stage === 'plan' && <section className="card"><span className="pill subtle">Adaptive activity plan · Draft</span><h2>{current.decision === 'reject' ? 'Sample activity rejected' : 'Your next classroom step'}</h2>{!current.decision ? <p>Select Accept, Modify, or Reject in Teacher Decision to prepare a draft plan.</p> : current.decision === 'reject' ? <p>No activity plan has been adopted. Return to Teacher Decision to reconsider or create an adapted activity.</p> : current.decision === 'modify' && !current.modification.trim() ? <p>Add your adapted activity in Teacher Decision to complete the draft.</p> : <><ol className="plan-list"><li><strong>Prepare</strong><p>{current.decision === 'modify' ? current.modification : 'Choose a familiar task and provide one worked example.'}</p></li><li><strong>Try together · 10 minutes</strong><p>Invite the learner to attempt a short first step. Offer a check-in and adjust the level of support.</p></li><li><strong>Reflect</strong><p>Ask what helped and record what you observed for the next session.</p></li></ol><div className="note">Teacher-reviewed demo draft. Timing and follow-up are sample suggestions; no automatic adaptation occurs.</div></>}</section>}
  <div className="page-actions">{index > 0 ? <Link className="button secondary" to={`/learners/${learner.id}/${steps[index - 1][0]}`}>← Back</Link> : <span />}{index < steps.length - 1 ? <Link className="button" to={`/learners/${learner.id}/${steps[index + 1][0]}`}>Continue to {steps[index + 1][1].toLowerCase()} →</Link> : <Link className="button" to="/">Return to dashboard</Link>}</div></>;
}
